name: Announcer
main: ch.minepvp.announcer.loader.BukkitLoader
version: 0.8

description: Announcer is a Message Information System that Informs the Player with Custom Messages over a Time Interval.
author: surtic86
website: https://github.com/MinePvP/Announcer

commands:
  announcer:
    description: Main Command